### ISSUE TITLE
Robot meshes not showing up as they should

### ISSUE THREAD

**Issue by JeroenDM** [JeroenDM/kuka_kr6r700_moveit_config#1]
When I launch the `demo.launch` file, I get the robot in RViZ as shown below:
![rviz_issue_kuka](https://user-images.githubusercontent.com/11537861/54476352-8cbc6b80-47fc-11e9-96e2-0ccccbf1d9e5.png)

**Comment by simonschmeisser** [comment]
try running it with LANG=C  or LC_NUMERIC=C eg
`LC_NUMERIC=C roslaunch demo.launch`

**Comment by JeroenDM** [comment]
Thanks for the reply! I totally forgot this issue was open...
My current solution is adding `export LC_NUMERIC="en_US.UTF-8"` to my bashrc.

**Comment by simonschmeisser** [comment]
it's most likely https://github.com/ros/urdfdom_headers/issues/45  you can vote at Ubuntu for an update
